#ifndef PERMISSIVESPELLCHECKER_GLOBAL_H
#define PERMISSIVESPELLCHECKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PERMISSIVESPELLCHECKER_LIBRARY)
#  define PERMISSIVESPELLCHECKER_EXPORT Q_DECL_EXPORT
#else
#  define PERMISSIVESPELLCHECKER_EXPORT Q_DECL_IMPORT
#endif

#endif // PERMISSIVESPELLCHECKER_GLOBAL_H
